server:
  port: 9191
  error:
    include-message: never

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: GATEWAY-SERVICE
  # rabbitmq:
  #   host: localhost          # RabbitMQ host (localhost if running on the same machine)
  #   port: 5672               # Default RabbitMQ port
  #   username: guest          # Default RabbitMQ username
  #   password: guest          # Default RabbitMQ password
  #   virtual-host: /          # Default virtual host ("/")
  #   listener:
  #     simple:
  #       retry:
  #         enabled: true       # Enable retry for message consumption
  #         initial-interval: 1000 # Initial retry interval in milliseconds
  #         max-attempts: 5     # Maximum number of retry attempts
  #       acknowledge-mode: auto # Auto acknowledgment of messages

  cloud:
    gateway:
      # default-filters:
        # - TokenRelay=
      routes:
        - id: PRODUCT-SERVICE
          uri: http://localhost:8090/
          predicates:
            - Path=/products/**, /inventories/**, /variations/**

        - id: AUTH-SERVICE
          uri: http://localhost:8080/
          predicates:
            - Path=/auth/**, /discount/**, /inventories/**, /variations/**
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         user-accounts-app-oidc:
  #           provider: spring
  #           client-id: user-accounts-app
  #           client-secret: secret
  #           authorization-grant-type: authorization_code
  #           redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
  #           scope: openid, profile, accounts.read
  #           client-name: user-accounts-app-oidc
  #       provider:
  #         spring:
  #           issuer-uri: http://localhost:9000
  #       resourceserver:
  #         jwt:
  #           jwk-set-uri: http://localhost:9000/oauth2/jwks
  #     authorizationserver:
  #       client:
  #         user-accounts-app:
  #           registration:
  #             client-id: "user-accounts-app"
  #             client-secret: "{noop}secret"
  #             client-authentication-methods:
  #               - "client_secret_basic"
  #             authorization-grant-types:
  #               - "authorization_code"
  #               - "refresh_token"
  #               - "client_credentials"
  #             redirect-uris:
  #               - "http://127.0.0.1:8080/login/oauth2/code/user-accounts-app-oidc"
  #               - "http://127.0.0.1:8080/authorized"
  #             post-logout-redirect-uris:
  #               - "http://127.0.0.1:8080/logged-out"
  #             scopes:
  #               - "openid"
  #               - "profile"
  #               - "accounts.read"
  #               - "accounts.write"
  #           require-authorization-consent: true

# spring:
#   application:
#     name: GATEWAY-SERVICE
#   config:
#     import: optional:configserver:http://localhost:8888

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"